### ISSUE TITLE
Error in Backend after Installation

### ISSUE THREAD

**Issue by blueamerican** [alexanderschnitzler/templavoila#1]
| Q                    | A
| -------------------- | -----
| Bug report?          yes
| Feature request?     no
| PHP version          5.6.28
| TYPO3 version        7.6.16
| TemplaVoilà version  7.6.2 

### Actual behaviour

After installing tv 7.6.2 and running the Upgrade Wizard, i get the following error when opening a page or a tv ce in the backend.

#1440685208: Broken data structure on field name tx_templavoila_flex. section without type or vice versa is not allowed

In the frontend everything works fine.

**Comment by blueamerican** [comment]
attached is the content of an example field "dataprot" of table tx_templavoila_dtastructure of an example fce
[datastructure-fce.zip](https://github.com/alexanderschnitzler/templavoila/files/907439/datastructure-fce.zip)

**Comment by alexanderschnitzler** [comment]
This is not a TemplaVoilà bug. The core handling of Flexforms changed and (unfortunately) you need to adjust your data structures manually.

Please see http://docs.templavoila.support/Changelog/7.6/Breaking-ConfigurationOfTypesInFlexforms.html for how to do this.

**Comment by blueamerican** [comment]
ok, i resolved this error by manually changing the structure.

But when try to open the ce in the backend, i get the following error:
#1437750231: The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7. Please set module[name]=module_name instead of using script=path/to/script.php in your TCA. (More information)

ok, this is also a thing solved with manual replacement, i guess.
https://wiki.typo3.org/Exception/CMS/1437750231

**Comment by alexanderschnitzler** [comment]
Yes, this is also a change in the TYPO3 core, that affects the TCA configuration in both PHP and files and Flexforms.
