### ISSUE TITLE
Unable to remove values from TCEforms config

### ISSUE THREAD

**Issue by vertexvaar** [alexanderschnitzler/templavoila#11]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     |no
| PHP version          | 7.0 (not relevant)
| TYPO3 version        | 7.6.18
| TemplaVoilà version  | dev-master

### Actual behaviour

I can not remove the marked <wizards> from the Form configuration, therefore i get an Exception in the Backend "The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7."

![Edit field](https://user-images.githubusercontent.com/5594393/27480832-1b86e770-581a-11e7-9427-a4d4a5344b07.png)

### Expected behaviour

I remove the whole <wizards> element from the configuration and i click update or safe the whole thing, then the element should not appear again

### Steps to reproduce the behaviour

- Add XML to the Form configuration of any element
- try to delete the just added element
- click on update
- the element appears again

### Current workaround

I can make use of the `ArrayUtility::mergeRecursiveWithOverrule` UnsetFeature, if i do not remove `<wizards type="array">`, but change the element to `<wizards>__UNSET</wizards>` which removes the element when the new values overrule the previous ones.

### Where should you look

Definitively in `\Schnitzler\Templavoila\Controller\Backend\AdministrationModule\ElementController::updateDataStructure`, where `$inDS` overrules `$dataStructure`. `$inDS` probably always contains the whole TCEforms array, because it is sent when updating the form, so unsetting keys in `$dataStructure[..]['config']` that do not exist in `$inDS[..]['config']` should be a possible solution.

**Comment by cweiske** [comment]
I've made a patch that solves the issue for us.
