### ISSUE TITLE
Correct placement of <title> tags of sections and containers

### ISSUE THREAD

**Issue by spackmat** [alexanderschnitzler/templavoila#5]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| PHP version          | 5.6
| TYPO3 version        | 7.6.18
| TemplaVoilà version  | 7.6.5

### Actual behaviour

When I leave the `<title>` tags sections and containers within the `<tx_templavoila>` tag, as the wizzard in "Modify DS/TO" implements it, they are not shown in the edit forms. When I move them one level up beneath the `<tx_templavoila>` tag (as suggested in the migration docs), they are shown in the edit forms, but not in the "Modify DS/TO" wizzard anymore.

### Expected behaviour

I would expect to have the titles of sections and containers shown in edit forms as well as th the "Modify DS/TO" wizzard.

### Steps to reproduce the behaviour

- create a aection and a container in "Modify DS/TO" wizzard.
- test their form and see that they don't show the titles
- move the `<title>` tags one level up beneath the `<tx_templavoila>` tag in the XML-DS
- test their form and see that they show the titles
- open the FCE in the "Modify DS/TO" wizzard and see that the tiles vanished

**Comment by alexanderschnitzler** [comment]
This is a bug. Unfortunately the title tag needs to be placed in or outside the `tx_templavoila` tag depending on whether we are dealing with a container/section or a regular element. This is due to the fact that the core handling changed in 7.6. On top of that the whole handling of sections changed as well.

I'll try to fix this soon but my priority is not on creating/managing data structures at the moment. Having my regular work as well, this fix can take some days.

**Comment by spackmat** [comment]
IMHO #4 is more critical, as it affects the editors workflow. This one here is more of a cosmetical issue, as #3 is, too.

**Comment by alexanderschnitzler** [comment]
@spackmat Can you please test with the latest merged commits from Christian Weiske? It should have fixed this issue.

**Comment by spackmat** [comment]
@alexanderschnitzler I downloaded the current master and moved the `title`-tag within the `tx_templavoila`-tag. Now the titles are shown in both the form and the "Modify DS/TO" wizzard. So yes, this fixes the bug for me. Thanks :)
