### ISSUE TITLE
Script to migrate old templavoila datastructures

### ISSUE THREAD

**Issue by cweiske** [alexanderschnitzler/templavoila#7]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no

We made a script that takes TYPO3 4.x TV datastructures and converts them into 7.6-compatible ones. We used it to fix 700 DS automatically with it.

Maybe you want to link it in the README or the docs. It's available at https://github.com/mogic-le/templavoila-76-fixer

**Comment by alexanderschnitzler** [comment]
I integrated this into the extension as an update script.
See c7c5798.

Thanks a bunch!
